### ISSUE TITLE
Able to upload Bill Of Materials?

### ISSUE THREAD

**Issue by xlfe** [CoretechR/ESP32-Handheld#2]
What a great project!

Any chance you would be able to upload a BOM please?

**Comment by CoretechR** [comment]
Sorry for taking so long but here's the BOM:
[ESP32 Handheld BOM.txt](https://github.com/CoretechR/ESP32-Handheld/files/4172634/ESP32.Handheld.BOM.txt)

**Comment by xlfe** [comment]
That's awesome - much appreciated @CoretechR 

You wouldn't happen to have Digikey Part Numbers too?

**Comment by CoretechR** [comment]
[Digikey Part Numbers.txt](https://github.com/CoretechR/ESP32-Handheld/files/4174643/Digikey.Part.Numbers.txt)
Please double check with the schematic. I already had some of the parts from other sources.

**Comment by xlfe** [comment]
@CoretechR that's great - thank you.
