### ISSUE TITLE
comments in code: save 80µA? and pinMode saves 10µA? how?

### ISSUE THREAD

**Issue by mahesh2000** [CoretechR/ESP32-Handheld#3]
hi, the `Memo.ino` file states that two of the lines save 10µA and 80µA. could you point me towards the documentation that has more info about this? thanks!
the lines are:
```
pinMode(0, OUTPUT); // don't change, -10µA???
```

and

```
rtc_gpio_pulldown_dis(ulp_toggle_num); // disable VCOM pulldown (saves 80µA)
```

**Comment by CoretechR** [comment]
These are values/improvements I made while monitoring the current with a multimeter.
The 80µA is probably caused by the VCOM being in a high state and the pulldown drawing current.
For the 10µA I have no idea, sorry. I was experimenting and this fix seemed to reduce current draw.

**Comment by mahesh2000** [comment]
hi, what is VCOM? i didn't see that name on any of the pins. also, i got it down to 40uA in sleep mode; it's still 4x what ESP32 claims. but still pretty good. i removed several parts (see photos of surgery) the UART chip (scraped the pins off, it was too difficult to remove), "LDO" (if you can call it that), various resistors, transistors, a power inductor, pretty much everything. i left the tantalum capacitor in place as it was between Vcc and GND. and for the test code i used yours and some more:
```
/**
 * Reduce power consumption of the ESP32 during sleep 
 * 
 * Mahesh Viswanathan, Jan 2020, mahesh@leakspotter.com
 * 
 */

// With just sleep code, consumption went down to 7.3mA, far too much.
// After removing the USB voltage regulator, a power inductor, UART. got it down to 40uA!

// probably don't need all these headers
#include "esp_sleep.h"
#include "driver/rtc_io.h"
#include "esp32/ulp.h"
#include "driver/adc.h"
#include "esp_wifi.h"
#include "esp_bt.h"
#include "WiFi.h" 
#include <esp_wifi.h>
#include "esp32-hal-bt.h"

// from https://www.savjee.be/2019/12/esp32-tips-to-increase-battery-life/
void goToDeepSleep()
{
  Serial.println("Going to sleep...");
  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
  btStop();


  adc_power_off();
  //esp_wifi_stop();  // this crashes
  esp_bt_controller_disable();

  #define DEEP_SLEEP_TIME 15
  // Configure the timer to wake us up!
  esp_sleep_enable_timer_wakeup(DEEP_SLEEP_TIME * 60L * 1000000L);

  // Go to sleep! Zzzz
  esp_deep_sleep_start();
}
/**
 * Save power. from https://desire.giesecke.tk/index.php/2018/02/15/deep-sleep-needs-wifi-switched-off-for-low-current-consumption/
 * To achieve maximum power saving during deep sleep it is apparently necessary to switch off Bluetooth and WiFi before calling esp_deep_sleep_start();
 */
static void power_things_off() {
  // esp_wifi_stop(); // this causes endless rebooting. why?
  esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_OFF);
  //WiFi.mode( WIFI_MODE_NULL );
  WiFi.mode(WIFI_OFF);
  btStop();
  adc_power_off();  

  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_0_GPIO_NUM);  //    36
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_1_GPIO_NUM); //    37
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_2_GPIO_NUM); //    38
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_3_GPIO_NUM); //    39
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_4_GPIO_NUM); //    34
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_5_GPIO_NUM); //    35
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_6_GPIO_NUM); //    25
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_7_GPIO_NUM); //    26
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_8_GPIO_NUM); //    33
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_9_GPIO_NUM); //    32
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_10_GPIO_NUM);  //   4
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_11_GPIO_NUM);  //   0
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_12_GPIO_NUM);  //   2
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_13_GPIO_NUM);  //   15
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_14_GPIO_NUM);  //   13
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_15_GPIO_NUM);  //   12
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_16_GPIO_NUM);  //   14
  rtc_gpio_isolate((gpio_num_t) RTCIO_CHANNEL_17_GPIO_NUM);  //   27

  //void rtc_gpio_force_hold_dis_all();
  rtc_gpio_force_hold_dis_all();

}




void print_wakeup_cause(esp_sleep_wakeup_cause_t cause) {
  Serial.print("Wakeup cause: ");
  if(cause == ESP_SLEEP_WAKEUP_UNDEFINED) Serial.println("ESP_SLEEP_WAKEUP_UNDEFINED"); //normal reset
  else if(cause == ESP_SLEEP_WAKEUP_ALL) Serial.println("ESP_SLEEP_WAKEUP_ALL");
  else if(cause == ESP_SLEEP_WAKEUP_EXT0) Serial.println("ESP_SLEEP_WAKEUP_EXT0");
  else if(cause == ESP_SLEEP_WAKEUP_EXT1) Serial.println("ESP_SLEEP_WAKEUP_EXT1"); //button A&B
  else if(cause == ESP_SLEEP_WAKEUP_TIMER) Serial.println("ESP_SLEEP_WAKEUP_TIMER"); //scheduled timer wakeup
  else if(cause == ESP_SLEEP_WAKEUP_TOUCHPAD) Serial.println("ESP_SLEEP_WAKEUP_TOUCHPAD");
  else if(cause == ESP_SLEEP_WAKEUP_ULP) Serial.println("ESP_SLEEP_WAKEUP_ULP");
  else if(cause == ESP_SLEEP_WAKEUP_GPIO) Serial.println("ESP_SLEEP_WAKEUP_GPIO");
  else if(cause == ESP_SLEEP_WAKEUP_UART) Serial.println("ESP_SLEEP_WAKEUP_UART"); 
}

/**
 * Entry point
 */
void setup(){
  delay(500); // "Unfortunately, the ESP32 software & hardware is not mature yet. There is a software or hardware bug that appears in both the ESP32 boards I tried when using the deep sleep mode. After a random number of wakes up, the ESP32 goes to sleep and it won’t wake up again. This bug can happen after a couple of wake ups or after 100. It is just random. One simple solution I discovered is to add a small delay of 500ms after waking up and before reading from the RTC memory. This way the project worked fine, but of course, the penalty we pay is reduced battery life, because the chip is in active mode for 500ms more in each wake-up. I think this bug will be resolved in the near future with a new software or hardware fix."
  // from https://www.hackster.io/nickthegreek82/esp32-deep-sleep-tutorial-4398a7  
  
  esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
  pinMode(0, OUTPUT); // don't change, -10µA???

  Serial.begin(115200);
  delay(100);
  print_wakeup_cause(cause);

  power_things_off();
  goToDeepSleep();
}

void loop(void){
  Serial.println("You should never get here.");
}
```
Original, virgin board:
![P_20200207_021143_p](https://user-images.githubusercontent.com/1047754/74067444-34ccbb80-49f1-11ea-9681-1593c364b248.jpg)

After ravaging -- look at all mess of parts desoldered and/or ripped out with needlenose pliers :-):
![P_20200207_033822_p](https://user-images.githubusercontent.com/1047754/74067456-3ac29c80-49f1-11ea-8cda-26506669fd2c.jpg)
![P_20200207_033756_p](https://user-images.githubusercontent.com/1047754/74067448-37c7ac00-49f1-11ea-9900-0c07082c2e19.jpg)

**Comment by CoretechR** [comment]
From the code I can't see any obvious problems. With such a board it might be difficult to reliably measure the current. It would be best to measure directly on the VCC supply of the ESP32. Maybe you can cut a trace there and connect your multimeter. It also can help to set different "suspicious" pins to a low state, for example tx/rx or anything that's connected to other ICs. However 40µA is a pretty good result already.

**Comment by mahesh2000** [comment]
yes, 40uA is good enough for me. that's why i'm not cutting out the rest. my multimeter is between my +3.3V and Vcc. the way i read the current is this:

```
3.3V _____/ _________ Vcc
       |          |
       |___ MM ___|

```

Close the switch. start the ESP32. put it into sleep mode. open the switch so the current now goes through the multimeter, which should be at the lowest setting. if you don't do that, the MM won't let enough current through and the ESP32 will not start properly. Once in sleep mode, it consumes very little current and this will give a good result. until the core wakes up again.

**Comment by CoretechR** [comment]
Just a tip, you can also put a diode in parallel with the multimeter. The diode will let enough current through during startup and in sleep mode the diode will block nearly all current.
https://electronics.stackexchange.com/questions/340330/measure-wide-range-of-current-800-%c2%b5a-1-5-a/340353#340353
Oh, and VCOM is just part of the sharp display interface that I used.

**Comment by mahesh2000** [comment]
does he mean i should use that circuit and put the MM across the 100 ohm resistor? it's not clear. it looks like an elegant solution.

**Comment by CoretechR** [comment]
If you put your multimeter in current mode you only need the diode, the resistor is only a shunt for measuring the current.
```
3.3V ______▷| ________ Vcc Pin
       |          |
       |___ MM ___|

```

**Comment by mahesh2000** [comment]
oh, nice!
