### ISSUE TITLE
modify pins

### ISSUE THREAD

**Issue by Hausenbourne** [CoretechR/ESP32-Handheld#5]
Hello friend, your project is really cool. I encountered some problems in the process of doing your project. Your SHARP_ VCOM pin is connected to IO2 pin of esp32, SHARP_ EXTMODE pin is connected to IO4 pin of esp32. Now I want to modify these two pins to connect to other IO ports of esp32. I have checked your code, but I can't find the relevant pin settings.

`#define SHARP_SCK  14`
`#define SHARP_MOSI 13`
`#define SHARP_SS   15`

**Comment by CoretechR** [comment]
Hi,
the VCOM pin is toggled with the low power core of the ESP32. You need to look at this file to change the pin but not all pins on the ESP32 are available for it. About the EXTMODE I have no clue. Maybe I forgot to configure it and it works accidentally. It is pulled to ground by the default Arduino pin setting. And in standby there might be a weak pullup. I am not so sure anymore.
